---
title: "R Notebook"
output: html_notebook
---
 

```{r}
textinprocess <- read.csv("C:/Users/recon/OneDrive - Nova Southeastern University/Desktop/Emergency Communication data/Data/temp files/textinprocess.csv")
library(tidytext)
library(dplyr)
tidy_textinprocess <- textinprocess %>%
  select(at,userName,review_content) %>%
  unnest_tokens("word", review_content)
data(stop_words)
top_review_words <-
+ tidy_textinprocess %>%
+ anti_join(stop_words) %>%
+ count(word) %>%
+ arrange(desc(n))

top_review_words <-
+ top_review_words[-grep("https|t.co|amp|rt",
+ top_review_words$word),]

top_20 <- top_review_words[1:20,]
top_review_words$word <- factor(top_review_words$word, levels = top_review_words$word[order(top_review_words$n,decreasing=TRUE)])
```
```{plot top 20 words}
library(ggplot2)
ggplot(top_20, aes(x=word, y=n, fill=word))+
geom_bar(stat="identity")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ylab("Number of Times Word Appears in Reviews")+
  xlab("")+
  guides(fill=FALSE)
```

```{r tf-idf}
tidy_textinprocess_tfidf <- textinprocess %>%
  select(at,userName,review_content) %>%
  unnest_tokens("word", review_content) %>%
  anti_join(stop_words) %>%
  count(word, at) %>%
  bind_tf_idf(word, at, n)
```

```{r unique words}
top_tfidf <- tidy_textinprocess_tfidf %>%
  arrange(desc(tf_idf))

top_tfidf$word[1]
```

```{r Making Dictionary}
time_dictionary <- c("time","delay","update","limit","current","prompt","alert","rarely","usually","sometimes","often","never","early","late","short","fast","slow","brief","old","ancient","elapse","swift","occasionally","always","minute","hour")
library(stringr)
time_reviews <- textinprocess[str_detect(textinprocess$review_content, time_dictionary),]
head(time_reviews$review_content)
time_reviews <- drop_NA(time_reviews)
time_reviews <- subset(time_reviews, select = -X)
```
```{r sentiment analysis with bing library}
reviews_sentiment <- tidy_textinprocess %>%
  inner_join(get_sentiments("bing")) %>%
  count(at, sentiment)
head(reviews_sentiment)
```

```{r distribution of sentiment histogram}
options(scipen=5)
ggplot(reviews_sentiment, aes(x = sentiment)) +
  geom_histogram(stat = 'count') +
  ggtitle("Distribution of Sentiment") +
  xlab("Positive & Negative Sentiment") +
  ylab("Sentiment Count") +
  ylim(c(0,900000))
  xlim(c(5,1000)) 
  scale_x_continuous(breaks = 10)
```

```{r plotting sentiment 2}
reviews_sentiment_plot <-
  tidy_textinprocess %>%
  inner_join(get_sentiments("bing")) %>%
  filter(sentiment=="negative") %>%
  count(at, sentiment)
``` 

```{r sentiment ggplot}
library(ggplot2)
ggplot(reviews_sentiment_plot, aes(x=at, y=n))+
  geom_line(color="red")+
  theme_minimal()+
  ylab("Frequency of Negative Words")+
  xlab("Date")
```
